# fly.toml app configuration file generated for natural-law on 2023-07-02T20:15:32-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "natural-law"
primary_region = "dfw"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
